### ISSUE TITLE
Positional encoding in LTAE?

### ISSUE THREAD

**Issue by kejie7243** [gastruc/AnySat#2]
Hello,

First, really thank you all for this great work!

I'm wondering why you use sinusoidal positional encoding in [LTAE](https://github.com/gastruc/AnySat/blob/0d68b7d62a9039f3b80c9dbf8124dbb92aee7b83/src/models/networks/encoder/utils/ltae.py#L37) where images (like Sentinel-2) at temporal dimension T_m do not have continuous and uniform gap. For example, two temporal adjacent images might be 10-day or 2-day away. It makes more sense to use sinusoidal encoding if the time series images are aggregated on a constant interval, but I'm not sure if all the dataset has been processed with this.

Also, I'm wondering if GeoPlex has any processing regarding cloud/snow removal. 

Thanks and happy holiday :)

**Comment by gastruc** [comment]
Hi,
I'm creating the sinusoïdal grid on the whole year and then take the good ones according to the date number in the year thanks to batch_positions argument in the forward of the ltae. In doing so, I take into account temporal shift. Also during all this work I've never used a cloud/snow removal assuming that the ltae is robust to these noises (in GeoPlex, we only have time series for S2). Thanks for your interest in this work!
